name: affiliana-cli

services:
  postgres:
    image: postgres:14
    container_name: affiliana-cli_database
    env_file: ../.env.development
    ports:
      - 6001:5432
    volumes:
      - ./db/pgsql:/var/lib/postgresql/data