version: '3.9'

name: market_research

services:
  postgres:
    image: postgres:14
    container_name: postgres-database
    env_file: ../.env.development
    ports:
      - 6001:5432
    volumes:
      - ./db/pgsql:/var/lib/postgresql/data