class NoDataFromSourceException(Exception): ...
class DataFetchError(Exception): ...
class AuthenticationError(Exception): ...
class DataFormatError(Exception): ...
class NotFoundError(Exception): ...