"""Remove url column from amazon_products table

Revision ID: 05a02ae4bcea
Revises: 7c70dfd4c4e4
Create Date: 2024-08-17 18:32:18.357863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '05a02ae4bcea'
down_revision: Union[str, None] = '7c70dfd4c4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazon_products', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_products', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
