"""Add amazon_commission_rate to niches table

Revision ID: 69fddf78810f
Revises: d68be93770c0
Create Date: 2024-08-22 18:02:08.851886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69fddf78810f'
down_revision: Union[str, None] = 'd68be93770c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niches', sa.Column('amazon_commission_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niches', 'amazon_commission_rate')
    # ### end Alembic commands ###
