"""Add amazon products table

Revision ID: fdc1e771cd13
Revises: 50bd683ba5ad
Create Date: 2024-08-16 21:26:51.818748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdc1e771cd13'
down_revision: Union[str, None] = '50bd683ba5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amazon_products',
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('reviews', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_table('niches_amazon_products',
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('amazon_product_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['amazon_product_asin'], ['amazon_products.asin'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('niche_id', 'amazon_product_asin')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('niches_amazon_products')
    op.drop_table('amazon_products')
    # ### end Alembic commands ###
