"""Make review related columns optional on amazon_products table

Revision ID: ad2c0afc4dcd
Revises: 8c91ccb12f54
Create Date: 2024-08-17 18:55:36.112879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad2c0afc4dcd'
down_revision: Union[str, None] = '8c91ccb12f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amazon_products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('amazon_products', 'reviews',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('amazon_products', 'bought_last_month',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amazon_products', 'bought_last_month',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('amazon_products', 'reviews',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('amazon_products', 'rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
