"""Add bought_last_month column to amazon_products table

Revision ID: 8c91ccb12f54
Revises: 05a02ae4bcea
Create Date: 2024-08-17 18:43:05.406076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c91ccb12f54'
down_revision: Union[str, None] = '05a02ae4bcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_products', sa.Column('bought_last_month', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazon_products', 'bought_last_month')
    # ### end Alembic commands ###
