"""Remove niche and subniche columns and make name not nullable for niches table

Revision ID: 50bd683ba5ad
Revises: 9cafc5246553
Create Date: 2024-08-13 20:44:22.759270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '50bd683ba5ad'
down_revision: Union[str, None] = '9cafc5246553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('niches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('niches', 'niche')
    op.drop_column('niches', 'subniche')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niches', sa.Column('subniche', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('niches', sa.Column('niche', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('niches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
