"""Add name column on niche table

Revision ID: 9cafc5246553
Revises: 48700093bcbf
Create Date: 2024-08-13 20:42:40.258052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cafc5246553'
down_revision: Union[str, None] = '48700093bcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niches', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niches', 'name')
    # ### end Alembic commands ###
