name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run Tests
        run: python scripts/run_tests.py --stop-containers-after